language: ruby
rvm: 2.3.0
cache: bundler
sudo: false

env:
  global:
    - SELENIUM_HOST=hub.browserstack.com
    - SELENIUM_PORT=80

    - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
    - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
    - secure: "L70bh0nIOaIoS7Va4Mr0GsdRlAjOILsNNrfwFDr3RjM2HaR3oeEKK1tJIEDEMamgBw6Ljhz7EWdDwt3bQ0HrhO9cI0kuzl+dA9Obf3+gucPSdi8QCZbjZDkwA56srsDEAMGAKkNWI1kmQTbPUPUoIuKmjj3Y3T68Ud2qi+hi5ag="
    - secure: "T7RSwd/aIYwsbuoyLPLzB0ZwOATDAFrpi9GQSVIbV1rZV2oGq+yisjeARUPyRfKTI0Q08CNgarLWfL/kONR6AL19XUD3Rm1+hag8bNixRYot2c65We6d40BMtPfZyO13kSWlTtDnzotYavhXoXujJNLfSjbdLdTlmy2m9Q0UfQc="

  matrix:
    - SELENIUM_BROWSER=firefox SELENIUM_VERSION=68
    - SELENIUM_BROWSER=firefox SELENIUM_VERSION=69

    - SELENIUM_BROWSER=opera SELENIUM_VERSION=12.15
    - SELENIUM_BROWSER=opera SELENIUM_VERSION=12.16

    - SELENIUM_BROWSER=opera SELENIUM_VERSION=62
    - SELENIUM_BROWSER=opera SELENIUM_VERSION=63

    - SELENIUM_BROWSER=ie SELENIUM_VERSION=6
    - SELENIUM_BROWSER=ie SELENIUM_VERSION=7
    - SELENIUM_BROWSER=ie SELENIUM_VERSION=8
    - SELENIUM_BROWSER=ie SELENIUM_VERSION=9
    - SELENIUM_BROWSER=ie SELENIUM_VERSION=10
    - SELENIUM_BROWSER=ie SELENIUM_VERSION=11

    - SELENIUM_BROWSER=edge SELENIUM_VERSION=17
    - SELENIUM_BROWSER=edge SELENIUM_VERSION=18

    - SELENIUM_BROWSER=safari SELENIUM_VERSION=5.1
    - SELENIUM_BROWSER=safari SELENIUM_VERSION=6.1
    - SELENIUM_BROWSER=safari SELENIUM_VERSION=7.0
    - SELENIUM_BROWSER=safari SELENIUM_VERSION=8.0
    - SELENIUM_BROWSER=safari SELENIUM_VERSION=10.1
    - SELENIUM_BROWSER=safari SELENIUM_VERSION=12.1

    - SELENIUM_BROWSER=ipad   SELENIUM_DEVICE="iPad 6th"
    - SELENIUM_BROWSER=iphone SELENIUM_DEVICE="iPhone 5S"
    - SELENIUM_BROWSER=iphone SELENIUM_DEVICE="iPhone 7"
    - SELENIUM_BROWSER=iphone SELENIUM_DEVICE="iPhone 8"

    - SELENIUM_BROWSER=android SELENIUM_DEVICE="Samsung Galaxy S10e"
    - SELENIUM_BROWSER=android SELENIUM_DEVICE="OnePlus 6T"
    - SELENIUM_BROWSER=android SELENIUM_DEVICE="Samsung Galaxy Tab S4"

    - SELENIUM_BROWSER=chrome SELENIUM_VERSION=75
    - SELENIUM_BROWSER=chrome SELENIUM_VERSION=76

#matrix:
#  allow_failures:

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version

before_script:
  - bundle exec rackup -p 9292 &
  - sleep 10

script:
  - bundle exec spec/runner.rb

notifications:
  irc: "irc.freenode.org#opal"
